<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_-- HTML EMAIL BODY --</name>
   <tag></tag>
   <elementGuidId>c3888949-572d-4f11-ab91-fb69852cb741</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#html_msg_body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='html_msg_body']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fa503001-4288-4cc0-948f-27efcba379b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>html_msg_body</value>
      <webElementGuid>3ab16666-4b0b-465d-87a5-d83cca919945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>HTML Email Message Body</value>
      <webElementGuid>0bf8551b-bcdd-42ba-8c40-8eedaa68d371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>e8321a53-b6a7-474d-b044-f8ee3ecc00ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>3a0c86a5-5715-406e-84b9-5f8b34616e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>html_msg_body</value>
      <webElementGuid>9a7ff74b-69a7-4e56-b18b-17d4306c3d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>984ba6a3-1607-4d92-983a-4b97c7af25b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    &lt;!-- HTML EMAIL BODY -->
                </value>
      <webElementGuid>4fbfb711-5b12-4e88-b4db-0cbba45cd3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;html_msg_body&quot;)</value>
      <webElementGuid>3bc50e81-8ede-47bf-b0c8-c6d663c725d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='html_msg_body']</value>
      <webElementGuid>fea60dfa-ecbe-4dde-bcae-5807076f8815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pills-html']/iframe</value>
      <webElementGuid>44d82406-61f8-4ab5-9e20-b7903a232b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATTACHMENTS'])[1]/following::iframe[1]</value>
      <webElementGuid>475f6c6c-60ca-4bbd-966b-9bbbc5b3064c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMTP_LOG'])[1]/following::iframe[1]</value>
      <webElementGuid>2cb37a70-3e5c-45a1-91f6-5ed793ffb004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Links Found'])[1]/preceding::iframe[2]</value>
      <webElementGuid>3fed348f-be77-4b07-a979-055d536ef67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOCKET_OPEN'])[1]/preceding::iframe[2]</value>
      <webElementGuid>1b2f288e-0dfa-4a94-83f9-953c8a7152f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt;!-- HTML EMAIL BODY -->']/parent::*</value>
      <webElementGuid>5b04e7af-84da-4640-84d6-647f2a28e79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/iframe</value>
      <webElementGuid>ec6d5170-863d-40bb-a17d-db4345a1ccb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'html_msg_body' and @title = 'HTML Email Message Body' and @name = 'html_msg_body' and (text() = '
                    &lt;!-- HTML EMAIL BODY -->
                ' or . = '
                    &lt;!-- HTML EMAIL BODY -->
                ')]</value>
      <webElementGuid>18252271-a4f1-4bee-9913-bfadd6a7713d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
