<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Self-Service_loginClientCode</name>
   <tag></tag>
   <elementGuidId>8ef07083-f97c-4adf-91df-aea140396afc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginClientCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginClientCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5bc298d2-0d18-4bbd-b7a2-ce02df1dbcfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f8234ee-3097-450a-807b-35744934ce72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4459e1dd-a5d2-4254-b140-5e5927d1d071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Client Code</value>
      <webElementGuid>bb467545-4e23-494d-a360-3a9cd33e97f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginClientCode</value>
      <webElementGuid>e2e58a4b-a024-4c1a-9d5d-919aa221518b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>loginOnKeyPress(event)</value>
      <webElementGuid>8db3cee6-d567-44f2-bde6-baaea5e3568b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginClientCode&quot;)</value>
      <webElementGuid>ad460cf5-0437-4160-9376-5a222a0b6014</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginClientCode']</value>
      <webElementGuid>57843c07-0fb8-43dc-ac57-0c6748e51b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input-container']/div/div/div/input</value>
      <webElementGuid>11a1a09c-6e6f-4241-83fb-52116073d448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>73aab2d4-4661-4519-bfd2-5362666f6900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Client Code' and @id = 'loginClientCode']</value>
      <webElementGuid>e1b59054-ec2b-417c-b8ef-7556e84dadd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
