<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Self-Service_loginEmployeeCode</name>
   <tag></tag>
   <elementGuidId>da781581-540d-42d5-bdcc-f6ba5546bb86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginEmployeeCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginEmployeeCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27122a1d-0911-494f-9277-5253a80c3327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72c66023-7796-4e46-9ee2-cf02dfa023fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>af8dfccb-b394-4922-972f-406a6e35e37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Employee Code</value>
      <webElementGuid>1aeb6a80-f0f8-4f7d-b7a5-ddb087f1158f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginEmployeeCode</value>
      <webElementGuid>0cbde508-30a9-41ac-853a-3f2a6634c939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>loginOnKeyPress(event)</value>
      <webElementGuid>c9778e05-50a4-47f3-8981-40639fae2b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginEmployeeCode&quot;)</value>
      <webElementGuid>7f680f95-55ca-4807-b0e6-17ceb588cfe9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginEmployeeCode']</value>
      <webElementGuid>626eb537-c4b2-49a5-8b1a-0142defbe5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input-container']/div/div[2]/div/input</value>
      <webElementGuid>9cf1bc89-ad9e-4c4b-ba98-beca5f6f5a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>3ca35f69-aa4d-4719-955e-b5c57f0797dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Employee Code' and @id = 'loginEmployeeCode']</value>
      <webElementGuid>c5fa9f2c-869e-41a9-bc03-f9695de6ec2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
