<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome to InsureMO_submitEbao</name>
   <tag></tag>
   <elementGuidId>c8b140b7-dda3-439a-b6cc-361d0c7df876</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submitEbao</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submitEbao']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da4aa9fe-6361-4ce9-86d1-5f7188fff5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>54cb3f6a-472a-4572-a4db-6ee10672a530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitEbao</value>
      <webElementGuid>c714722f-f781-4aa2-a603-c1377f1432f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accesskey</name>
      <type>Main</type>
      <value>l</value>
      <webElementGuid>40fffed5-4bea-41a0-8a7a-b6ffc89e64c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>07ab9731-8050-4f63-821e-66f7911812ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>67a61fac-918d-4c7d-b099-3dc697e56453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cb1f023f-4f03-4282-8aa8-dce4f8d2eb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitEbao&quot;)</value>
      <webElementGuid>a169a21e-70ca-4c8d-af19-fc742a74057f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submitEbao']</value>
      <webElementGuid>103b7fe0-a655-4a26-95ab-5324dba72c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='signin-form']/div[5]/input</value>
      <webElementGuid>f771ca2a-f5bc-405c-bcbc-7ee5eef83dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>6666d434-d45b-47e3-b6f5-8df81bf4561f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'submitEbao' and @type = 'submit']</value>
      <webElementGuid>ac73efed-b86e-4090-86a8-2d3ac11c2eb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
