<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Platform</name>
   <tag></tag>
   <elementGuidId>4a92709e-ac99-4036-a219-c597af0db10c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='katalon_header']/section[2]/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>355690d5-5abc-46a8-b284-27a3f89c3f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top_nav_title</value>
      <webElementGuid>80862229-897d-4b16-abf7-796cd9fa5e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-traffic-agent-hoverable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8044e6b8-d8e7-4f05-b33e-3056933c49eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-traffic-agent-last-action-id</name>
      <type>Main</type>
      <value>6f11d96a-76ee-4c1c-9703-0582c0375b92</value>
      <webElementGuid>22fa39d0-3adc-4b0f-962d-3356757a29f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-hoverable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c37189ab-69c1-49c3-a0d7-1ca08e0963fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-last-action-id</name>
      <type>Main</type>
      <value>ae37d88c-3ca6-4dd4-a295-d178ddfa9dfb</value>
      <webElementGuid>a92761af-7e21-4a54-aef5-288c7e3d3d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Platform</value>
      <webElementGuid>4ac22f19-5802-49bf-8aaa-4dba445156fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon_header&quot;)/section[@class=&quot;rebrand_header fixed_top&quot;]/div[@class=&quot;wrap_container&quot;]/div[@class=&quot;left_logo_and_topnav&quot;]/div[@class=&quot;katalon_topnav&quot;]/div[@class=&quot;top_nav_item have_child_menu&quot;]/div[@class=&quot;top_nav_title&quot;]</value>
      <webElementGuid>cdf0ebc5-6a6f-44d9-8911-3b8ea59895dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='katalon_header']/section[2]/div/div/div/div[2]/div</value>
      <webElementGuid>8fdb4982-50d7-4179-af05-dc0054db362d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low cost, high ROI'])[1]/following::div[3]</value>
      <webElementGuid>02e2e808-1971-4543-9d67-4571bb159f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Innovation &amp; AI'])[1]/following::div[5]</value>
      <webElementGuid>eeba5a82-91fc-419c-8764-ff4b158c7a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platform'])[2]/preceding::div[1]</value>
      <webElementGuid>4b3966e8-c98e-4a79-8876-82f7f53c17c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platform Overview'])[1]/preceding::div[4]</value>
      <webElementGuid>d2dfc691-4d6c-43a4-ac77-de8268363439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Platform']/parent::*</value>
      <webElementGuid>c203113a-25d9-4dc0-af09-2b4c616b0026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>2a78057f-5209-4ae1-868c-335294becd19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Platform' or . = 'Platform')]</value>
      <webElementGuid>ca427921-e87b-445d-9149-d71286586637</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
