<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thank you for your orderYour order has _f1f997</name>
   <tag></tag>
   <elementGuidId>8c42e4c7-9538-4113-9f9c-7ef9f6a396c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout_complete_container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkout_complete_container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c4d10f2f-8410-4f15-962d-3b9b9ab88958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkout_complete_container</value>
      <webElementGuid>b462a3b6-1ca4-4bad-bd8f-a8769ee665db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkout_complete_container</value>
      <webElementGuid>86a94c9a-1a46-445f-b97d-c9aebf09dfda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you for your order!Your order has been dispatched, and will arrive just as fast as the pony can get there!Back Home</value>
      <webElementGuid>7fab65b8-4cd5-4568-a65d-93e34f7bac46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout_complete_container&quot;)</value>
      <webElementGuid>f012b15a-5b96-4aef-96db-6566602b4c58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='checkout_complete_container']</value>
      <webElementGuid>89cb0137-1c5e-4b8f-aee2-f74b993f2e41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contents_wrapper']/div[2]</value>
      <webElementGuid>b0b7254f-f41b-4fb2-96c7-12860a34018d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout: Complete!'])[1]/following::div[1]</value>
      <webElementGuid>69daf500-b5a7-4785-8a52-e694bdf90991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Swag Labs'])[2]/following::div[3]</value>
      <webElementGuid>1bacd121-4969-4875-8701-1ec22c95f7f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>caf84f10-fd95-441d-8dfb-a06d04e45fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'checkout_complete_container' and (text() = 'Thank you for your order!Your order has been dispatched, and will arrive just as fast as the pony can get there!Back Home' or . = 'Thank you for your order!Your order has been dispatched, and will arrive just as fast as the pony can get there!Back Home')]</value>
      <webElementGuid>e7f3d711-1ef6-4460-9ae2-50a6a0db5cca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
